---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas01-pv-data
spec:
  capacity:
    storage: 2Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volume1/media
    server: 10.0.0.129
    readOnly: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas01-pvc-data
spec:
  volumeName: nas01-pv-data
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Ti
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: depl-jellyfin-web
spec:
  selector:
    matchLabels:
      app: jellyfin-web
  replicas: 1
  template:
    metadata:
      name: jellyfin-web
      labels:
        app: jellyfin-web
    spec:
            # securityContext:
            #  fsGroup: 911
      volumes:
        - name: nfs-data
          persistentVolumeClaim:
            claimName: nas01-pvc-data
      containers:
        - name: jellyfin-web
          image: lscr.io/linuxserver/jellyfin:latest
          ports:
            - containerPort: 8096
          volumeMounts:
            - mountPath: /data/tvshows
              name: nfs-data
              subPath: shows
            - mountPath: /data/movies
              name: nfs-data
              subPath: movies
            - mountPath: /config
              name: nfs-data
              subPath: config/jellyfin/
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 10.0.0.224
  selector:
    app: jellyfin-web
  ports:
    - name: http-access
      protocol: TCP
      port: 80
      targetPort: 8096
